# **Numpy**

* 숫자데이터의 효율적 처리를 위한 라이브러리
    * 빠르고 메모리 효율적이 배열 연산의 지원
    * 파이썬의 기본 리스트보다 강력한 다차원 배열
* 데이터 분석에 최적화된 특징을 가지고 있음
    * 벡터, 텐서 연산을 효과적으로 처리할 수 있음. 내부적으로 C로 되어 있어서 연산 속도가 빠르다.
    * 브로드케스팅: 배열 간 크기가 다른 경우에도 연산 가능
    * 유연한 인덱싱  

**<ndarray와 list>**  
* ndarray는 list와 유사하지만 여러 면에서 더 효율적인 데이터 구조이다.
    * 동종 데이터 저장: Numpy 배열은 모든 원소가 동일한 데이터 타입이어야 한다.
        * 반면 파이썬 리스트는 다양한 데이터 타입을 혼합해서 저장할 수 있다.
    * 빠른 연산 속도: C로 구성됨
    * 메모리 효울성: 배열의 크기가 고정되어 있어 리스트보다 메모리를 효율적으로 사용한다.
    * 다차원 배열: Numpy 배열은 1차원 벡터, 2차원 행렬, 다차원 텐서 등 다양한 차원의 데이터를 다룰 수 있다.
    * 벡터화 연산 지원: 배열 연산은 반복문 없이 전체 배열에 대해 수학적 연산 수행가능.

**<ndarray 생성 방법>**  
 * 함수 생성 방법

   ```python
   import numpy as np
   arr = np.array([1, 2, 3, 4])  
   
   
   ```
   
 
 * 특정한 값을 가진 배열 생성

   ```python
   arr = np.zero(5) # 모든 크기가 0인 크기가 (5)인 배열
   arr = np.ones((2, 3)) # 모든 값이 1인 크기가 2X3인 배열
   full = np.full((3, 3), 7) #모든 값이 7인 크기가 3X3인 배열  
   


    ```

* 연속된 값을 가진 배열 생성

    * (1) arrange 함수: 특정 간격의 숫자 배열을 생성합니다. 파이썬의 range와 유사하지만 배열 형태로 반환
      ``` python
      np.arange(start, stop, step, dtype=None)  
      

      ```
      ```python
      arr1 = np.arange(5) # [0 1 2 3 4]
      arr2 = np.arange(1, 10) # [1 2 3 4 5 6 7 8 9]
      arr3 = np.arange(0, 10, 2) # [0 2 4 6 8]
      arr4 = np.arange(0, 1, 0.2) # [0. 0.2 0.4 0.6 0.8]   
      

      ```
* 다양한 함수를 이용하여 생성할 수 있음.

In [12]:
import numpy as np

In [16]:
import time

# 리스트와 배열의 연산 속도 비교
lst = list(range(1, 1000001))
arr = np.array(lst)

start_time = time.time()
lst_result = [x * 2 for x in lst]
print("리스트 연산 시간:", time.time() - start_time)

start_time = time.time()
arr_result = arr * 2
print("Numpy 배열 연산 시간:", time.time() - start_time)

#컴퓨터 환경에 따라 연산 시간이 달라져 결괏값도 달라진다.

리스트 연산 시간: 0.126908540725708
Numpy 배열 연산 시간: 0.003026247024536133


In [20]:
0.126908540725708/0.003026247024536133

#41배나 빠른 것을 알 수 있다. (파이썬은 느리다.)

41.93594894823919

In [24]:
# 리스트로부터 배열 생성 

arr_1d = np.array([10, 20, 30, 40])  # 1차원 배열
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])  # 2차원 배열

print(arr_1d)
print(arr_2d)

# 2차원배열에서는 같은 위치에 있는 것이 열이 된다는 것을 알 수 있음

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [30]:
# 특정한 값으로 채원 배열 생성

# 0으로 채워진 배열 생성
arr_1d = np.zeros(5)  # 1차원 배열
arr_2d = np.zeros((2, 3), dtype = int)  # 2차원 배열
print(arr_1d)
print(arr_2d)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]


In [32]:
# 1차원에는 float자료형이어서 .이 찍혀있다.

In [34]:
# 1으로 채워진 배열 생성
arr_1d = np.ones(5)  # 1차원 배열
arr_2d = np.ones((2, 3))  # 2차원 배열
print(arr_1d)
print(arr_2d)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [36]:
# 연속죈 숫자로 구성된 배열 만들기

arr = np.arange(0, 11, 2)  # 0부터 10까지 2 간격
print(arr)

[ 0  2  4  6  8 10]


In [38]:
arr = np.arange(0, 11, 0.5)  # 0부터 10.5까지 0.5 간격
print(arr)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5]


In [40]:
# 콤마가 없고 일정 간격으로 만들어지는 것을 볼 수 있음.
# arange(시작, 끝(자신 미포함), 간격) 으로 이루어져 있으며 이는 슬라이싱과 비슷한 것으로 보임.

In [44]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [46]:
#linspace(시작, 끝, 개수) 인데, 간격을 생각해서 리스트 원소의 개수를 정해야 한다.
# 되도록이면 arange()에 익숙해지는 것이 좋다고 한다.

In [42]:
arr = np.linspace(0, 1, 10) # 간격을 잘 정해야 하는 이유
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [48]:
# 위와 같이 값이 나올 수 있으니 주의하자.

# **차원**

* 차원은 배열에서 데이터가 배열된 축(axis)의 개수를 말한다.
 * 1차원 배열 = 벡터 : 단일 축으로 구성된 배열 ([1, 2, 3])
 * 2차원 배열 = 행렬 : 행과 열로 구성된 배열 (우리가 아는 2차원 배열)
 * 3차원 배열 = 텐서 : 2차원 배열이 레이어처럼 여러개로 겹쳐 있다
     * (사진 처리할때의 RGB값을 나타낼때 쓰임. 텐서 하나가 픽셀이 됨.)
 * ndim : 배열의 차원을 확인하는 함수
 * shape :  배열의 모양을 확인하는 함수


 ## **축(axis)**  
 : 매우 중요함!  
 * 2차원 배열을 기준으로 axis = 0은 행을, axis = 1은 열을 나타낸다.
     * 주로 연산 방향을 나타낸다.  (예: axis = 1로 설정하고 각 열의 평균을 구하기 등)

 ### **차원 변경 함수**  
 : reshape, flatten, squeeze 등의 함수를 이용하여 차원을 변경할 수 있다.  
 * arr.reshape(newshape): arr의 차원을 newshape로 변경함
     * 단, 기존 차원에서 변경할 수 있는 shape여야 함
 * flatten 함수: 다차원 배열을 1차원으로 평탄화 하는데 사용 ((3, 4)를 (12, ) 로 변환)
 * squeeze 함수: 크기가 1인 차원을 제거 (예: (1, 3, 1)인 배열이 있다면 (3, )으로 변환)

 
 

In [52]:
# 차원 형태 확인 
arr1 = np.array([1, 2, 3, 4, 5])
print("차원:", arr1.ndim)
print("형태:", arr1.shape)

# (5, ) = 튜플 (크기가 1인 튜플; 콤마(,) 포함)


차원: 1
형태: (5,)


In [54]:
# 2. 2차원 배열 생성
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("차원:", arr2.ndim)
print("형태:", arr2.shape)

차원: 2
형태: (2, 3)


In [60]:
len(arr2.shape) # 차원은 이렇게 구할 수도 있다. len()을 쓰면 차원만 나오게 됨.

2

In [58]:
# 3. 3차원 배열 생성
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)
print("차원:", arr3.ndim)
print("형태:", arr3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
차원: 3
형태: (2, 2, 2)


In [64]:
# 차원 변경 reshape(행, 열) 사용

arr = np.array([1, 2, 3, 4, 5, 6]) # (6,)
reshaped = arr.reshape(2, 3)  # 2행 3열로 변환
print(arr)
print(reshaped)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [66]:
reshaped = arr.reshape(4, 2)  # 4행 2열로는 바꿀 수 없음
print(reshaped)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [68]:
# 왜? 4행 2열로 하려면 원소가 8개 필요한데 부족하기 때문이다.
# 그러나 하나하나 원소 개수를 세고 있을 수는 없다. 그렇다면?

In [70]:
reshaped = arr.reshape(-1, 2)  # -1을 넣으면 나머지 차원에 맞게 변환됨
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [72]:
# 다시 펼치기 flatten()

flattened = reshaped.flatten()
print(reshaped)
print(flattened)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [74]:
arr = np.array([[[1], [2]], [[3], [4]]])  # (2, 2, 1) 형태
print(arr.shape)
print(arr)
squeezed = np.squeeze(arr)  # 크기가 1인 축 제거
print("squeeze 후:\n", squeezed, squeezed.shape)

(2, 2, 1)
[[[1]
  [2]]

 [[3]
  [4]]]
squeeze 후:
 [[1 2]
 [3 4]] (2, 2)


### **유니버셜 함수**
 유니버셜 함수는 요소별 연산을 수행한다.   
 기본적인 산술 연산부터 삼각 함수, 지수 함수 등 다양한 수학 연산을 지원한다.  
   * 산술 연산, 거듭 제곱 등...

In [91]:
# 배열 간 사칙연산

arr1 = np.array([1,2,3])
arr2 = np.array([-1,-2,-3])

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))

[0 0 0]
[2 4 6]
[-1 -4 -9]
[-1. -1. -1.]


In [93]:
# 이렇게 할 수도 있다. 훨씬 편리하다.

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[0 0 0]
[2 4 6]
[-1 -4 -9]
[-1. -1. -1.]


In [188]:
# 지수, 로그, 제곱근, 절댓값

print(np.sqrt(arr1))  # 제곱근
print(np.exp(arr2))  # 지수 
print(np.log(arr1))  # 로그 
print(np.log10(arr1))  # 로그
print(np.abs(arr2))  #절댓값

[[1.        ]
 [1.41421356]
 [1.73205081]]
[[ 2.71828183  7.3890561  20.08553692]]
[[0.        ]
 [0.69314718]
 [1.09861229]]
[[0.        ]
 [0.30103   ]
 [0.47712125]]
[[1 2 3]]


### **브로드캐스팅**
 브로드캐스팅은 서로 다른 크기의 배열 간 연산을 가능하게 한다.  
 작은 배열이 자동으로 확자오디어 큰 배열과 동일한 형태로 변환된 후 연산이 수행된다.  
  * (3,)과 (1,)을 합치면 (3,)이 된다.
  * (1, 3)과 (3, 1)을 합친다면? (3, 3)이 된다. 즉, **더 큰쪽이 있으면 그것을 기준으로 작은 쪽을 늘린다!**  

In [ ]:
# 스칼라 * 배열

arr1 = np.array([1,2,3])
arr2 = np.ones((3,3))

display(arr1) # display: Jupyter Notebook에서 데이터를 원본에 가깝게 출력하는데 사용
display(arr2)

In [106]:
 arr

array([[[1],
        [2]],

       [[3],
        [4]]])

In [ ]:
# 이렇게 나오는 것도 디스플레이로 나오는 것이다.

In [108]:
print(arr)

[[[1]
  [2]]

 [[3]
  [4]]]


In [110]:
display(arr1 * 10)
display(arr2 - 1)

array([10, 20, 30])

array([-2, -3, -4])

In [112]:
# 배열과 배열 합치기

arr1 = np.array([1,2,3])
arr2 = np.ones((3,3))
display(arr1)
display(arr2)

array([1, 2, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [114]:
display(arr1 + arr2)

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [116]:
arr1 = np.array([1,2,3]).reshape(-1, 1)
arr2 = np.ones((3,3))
display(arr1)
display(arr2)
display(arr1 + arr2)

array([[1],
       [2],
       [3]])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [118]:
arr1 = np.array([1,2,3]).reshape(-1, 1)
arr2 = np.array([1,2,3]).reshape(1, -1)
display(arr1)
display(arr2)
#display(arr1 + arr2)

array([[1],
       [2],
       [3]])

array([[1, 2, 3]])

In [120]:
display(arr1 + arr2)

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

### **통계 함수**
  Numpy는 다양한 통계 함수 및 메서드를 제공한다.

In [122]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
display(arr)

array([[10, 20, 30],
       [40, 50, 60]])

In [124]:
print(np.mean(arr))
print(np.mean(arr, axis = 0))
print(np.mean(arr, axis = 1))

35.0
[25. 35. 45.]
[20. 50.]


In [126]:
print(np.std(arr))
print(np.std(arr, axis = 0))
print(np.std(arr, axis = 1))

17.07825127659933
[15. 15. 15.]
[8.16496581 8.16496581]


In [128]:
print(np.median(arr))
print(np.median(arr, axis = 0))
print(np.median(arr, axis = 1))

35.0
[25. 35. 45.]
[20. 50.]


In [130]:
# 메서드 활용 - 축을 기준으로 평균을 구함.
print(arr.mean())
print(arr.mean(axis = 0))
print(arr.mean(axis = 1))

35.0
[25. 35. 45.]
[20. 50.]


In [132]:
# ndarray가 아니여도 함수를 쓸 수 있습니다.
L = [1,2,3]
print(np.mean(L))

2.0


## **인덱싱과 슬라이싱**
  일반적인 경우에는 파이썬의 기본 인덱싱 및 슬라이싱과 같다.
   * 1차원 : 같음
   * 2차원 : [row_idx, col_idx] 형태로 행과 열 인덱스를 따로 접근한다.
   * 2차원 이상 : 각 차원을 ' , '로 구분하여 접근한다.
       * 3차원 : [idx1, idx2, idx3]

### 1차원 배열



In [152]:
arr = np.array([10, 20, 30, 40, 50])

# 기본 인덱싱
print(arr[0])  # 첫 번째 요소: 10
print(arr[-1])  # 마지막 요소: 50

# 슬라이싱: 1번 인덱스부터 3번 인덱스까지
print(arr[1:4])  # [20 30 40]

# 슬라이싱: 처음부터 3번 인덱스까지
print(arr[:4])  # [10 20 30 40]

# 슬라이싱: 2번 인덱스부터 끝까지
print(arr[2:])  # [30 40 50]

10
50
[20 30 40]
[10 20 30 40]
[30 40 50]


### 2차원 배열

In [154]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 기본 인덱싱: 첫 번째 행, 두 번째 열
print(arr_2d[0, 1])  # np.array는 한번에 두 개 쓸 수 있다.
print(arr_2d[0][1])  # 리스트는 이렇게 두 번 써야한다

# 슬라이싱: 두 번째 행부터 끝까지, 첫 번째 열부터 두 번째 열까지
print(arr_2d[1:, :2]) # 슬라이싱도 한번에 가능

# 인덱싱과 슬라이싱 혼합
print(arr_2d[1:, 1]) # 혼합도 가능

2
2
[[4 5]
 [7 8]]
[5 8]


## **팬시 인덱싱**

  팬시 인덱싱을 활용하면 여러 인덱스를 한 번에 지정하여 데이터를 선택할 수 있다.
   * 인덱스로 리스트를 사용한다.
   * [row_idx, col_idx] 각각에 대응대는 값을 가져온다.
    

### 1차원 배열

In [156]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 2, 4]]) # 주의: 인덱스를 리스트 형태로 갖고 있는 것임
indices = [1, 3]
print(arr[indices])

[10 30 50]
[20 40]


### 2차원 배열

In [220]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 여러 행, 여러 열을 한 번에 선택할 수 있다
print(arr_2d[[0, 2], [1, 2]])  
# [2 9] (1번째 행, 2번째 열; 2번째 행, 3번째 열)
# [] 괄호 하나가 2의 (행, 열)을 뜻하는게 아니다.
# [a, b] [c, d] 이렇게 있으면 왼쪽에 있는 숫자(a, c)들이 왼쪽 숫자의 좌표를 뜻한다. 헷갈리지 말자.

# 특정 행을 선택하고, 각 행에서 여러 열 선택하기
print(arr_2d[[0, 1], [0, 2]])

# 2차원에서의 인덱싱과 슬라이싱 혼합 
print(arr_2d[[0,1], :]) #:만 쓰면 해당 차원에서는 모든 데이터를 가져온다고 할 수 있음

[2 9]
[1 6]
[[1 2 3]
 [4 5 6]]


## **비교 연산과 마스킹** 
  부울 배열을 이용하여 인덱싱을 하는 방법이다.
   * 같은 위치에 있는 인덱스 중에서 True인 요소만 가져온다.
   * 부울 배열은 비교 연산을 통해 생성하며, 유니버셜 함수를 지원한다.

### 1차원 배열

In [160]:
arr = np.array([10, 20, 30, 40, 50])

# 조건: 값이 30 이상인 요소 선택
mask = arr >= 30 # 이게 마스크의 조건
print(mask)  # [False False  True  True  True]

[False False  True  True  True]


In [164]:
print(arr[mask])  #  마스크 씌우기

[30 40 50]


In [166]:
# 30 이상인 수만 선택되었다.

In [172]:
print(mask.sum()) # True인 요소 개수. len이 아니라 sum으로 구함 주의.

3


In [178]:
# 조건: 값이 20 이상 40 이하인 요소 선택
# 이건 쉬워 보여서 직접 풀기로 한다.
mask = (arr >= 20) & (arr <= 40)
print(arr[mask])

# 20 < x < 40 처럼 한꺼번에 적으면 에러가 난다. 주의!

[20 30 40]


### 2차원 배열

In [180]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 조건: 값이 5 이상인 요소 선택
mask = arr_2d >= 5
print(mask)

[[False False False]
 [False  True  True]
 [ True  True  True]]


In [182]:
print(arr_2d[mask])

[5 6 7 8 9]


In [184]:
# 조건: 값이 4 이상인 요소를 0으로 변경
arr_2d[arr_2d >= 4] = 0 # arr[mask] = 바꿀 값
print(arr_2d)

[[1 2 3]
 [0 0 0]
 [0 0 0]]
